name: import-apiconfig
on:
  workflow_dispatch:
    inputs:
      config-file:
        description: 'config file need to be imported'
        type: string
        required: true
      api-defition:
        description: 'api definition file need for config file'
        type: string
        required: true
jobs:
  import_api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: import graphql definitions
        run: |
          docker run --name apim-cli \
          -v ${{ github.workspace }}/${{ inputs.config-file }}:/${{ inputs.config-file }} \
          -v ${{ github.workspace }}/${{ inputs.api-defition }}:/${{ inputs.api-defition }} bvieira123/apim-cli:1.14.4  \
          apim api import -h ${{ vars.APIM_INSTANCE_IP }} -u ${{ vars.APIM_INSTANCE_USER }} -port 8075 \
          -p ${{ secrets.APIM_INSTANCE_PASSWORD }} -c /${{ inputs.config-file }}
      - name: check container logs
        run: |
          docker logs apim-cli
      - name: cleanup
        run: |
          docker rm apim-cli