name: Update API Config
on:
  push:
    branches:
      - main

jobs:
  update_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changes
        id: get_changes
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          CHANGES=$(echo "$CHANGES" | grep -vE '\.ya?ml$')
          echo $CHANGES
          CONFIG_FILES=$(echo \"$CHANGES\" | grep -E '.*-config\.json$' | paste -sd ',')
          API_DEFINITION=$(echo \"$CHANGES\" | grep -vE '(-config\.json|\.graphqls|\.yaml|\.yml)$' | paste -sd ',')
          GRAPHQL_SCHEMAS=$(echo \"$CHANGES\" | grep -E '*\.graphqls$' | paste -sd ',')
          CONFIG_FILES=$(echo "$CONFIG_FILES" | sed 's/\.[^.]*$//')
          API_DEFINITION=$(echo "$API_DEFINITION" | sed 's/\.[^.]*$//')
          GRAPHQL_SCHEMAS=$(echo "$GRAPHQL_SCHEMAS" | sed 's/\.[^.]*$//')
          echo "CONFIG_FILES=$CONFIG_FILES" >> $GITHUB_ENV
          echo "API_DEFINITION=$API_DEFINITION" >> $GITHUB_ENV
          echo "GRAPHQL_SCHEMAS=$GRAPHQL_SCHEMAS" >> $GITHUB_ENV

      - name: Process API Definitions
        if: env.API_DEFINITION != '' && env.CONFIG_FILES == ''
        run: |
          IFS=',' read -ra ADDR <<< "$API_DEFINITION"
          for value in "${ADDR[@]}"; do
            echo "Processing $value"
            filename="${value##*/}"
            matches=$(grep -rl "$filename" $PWD/*.json)
            CONFIG_FILES="$CONFIG_FILES,$matches"
          done
          echo "CONFIG_FILES=$CONFIG_FILES" >> $GITHUB_ENV

      - name: Process GraphQL Schemas
        if: env.GRAPHQL_SCHEMAS != '' && env.CONFIG_FILES == ''
        run: |
          IFS=',' read -ra ADDR <<< "$GRAPHQL_SCHEMAS"
          for value in "${ADDR[@]}"; do
            echo "Processing $value"
            filename="${value##*/}"
            matches=$(grep -rl "$filename" $PWD/*.json)
            CONFIG_FILES="$CONFIG_FILES,$matches"
          done
          echo "CONFIG_FILES=$CONFIG_FILES" >> $GITHUB_ENV

      - name: Display Config Files
        run: echo "$CONFIG_FILES"
